# Generated by Django 2.1.4 on 2019-01-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
                ('formato', models.CharField(blank=True, max_length=255, null=True)),
                ('hash', models.CharField(blank=True, max_length=255, null=True)),
                ('imagem_url', models.CharField(blank=True, max_length=255, null=True)),
                ('origin_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tamanho', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'imagem',
                'managed': False,
            },
        ),
    ]
