# Generated by Django 2.1.4 on 2019-03-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedUsers',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('login', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'imported_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Priority1',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'priority1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Priority2',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'priority2',
                'managed': False,
            },
        ),
    ]
