# Generated by Django 2.1.4 on 2019-03-23 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impusers', '0002_importedusers_priority1_priority2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importedusers',
            options={'managed': False, 'verbose_name': 'Usuário importado', 'verbose_name_plural': 'Usuários importados'},
        ),
    ]
